name: Auto Release from Changelog

on:
  push:
    branches: [main]
    paths:
      - '**.cs'
      - '**.csproj'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        project: [NcGtk, NcWpf]
        include:
          - os: ubuntu-latest
            project: NcGtk
            output: NcGtk.zip
          - os: windows-latest
            project: NcWpf
            output: NcWpf.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install GTK (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y libgtk-3-dev pkg-config

      - name: Restore dependencies
        run: dotnet restore NetworkChat.sln

      - name: Build
        run: dotnet build ${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Release --output ./publish/${{ matrix.project }}

      - name: Archive
        run: zip -r ${{ matrix.output }} ./publish/${{ matrix.project }}

      - name: Upload ZIP to workspace
        run: mv ${{ matrix.output }} ${{ github.workspace }}/

      - name: Create Git Tag
        run: |
          git config user.name "github-actions"
          git config user.email "damian@morozov33.ru"
          VERSION=${{ steps.changelog.outputs.version }}
          git tag $VERSION
          git push origin $VERSION
        env:
          GH_PUSH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        continue-on-error: false

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from CHANGELOG.md
        id: changelog
        run: |
          VERSION=$(grep -m1 '^## \[' CHANGELOG.md | sed -E 's/^## \[([0-9]+\.[0-9]+\.[0-9]+)\].*/v\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.changelog.outputs.version }}
          name: Release ${{ steps.changelog.outputs.version }}
          body_path: CHANGELOG.md
          files: |
            NcGtk.zip
            NcWpf.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}