name: Build Linux application

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install GTK (Linux only)
        run: sudo apt update && sudo apt install -y libgtk-3-dev pkg-config
      - name: Restore NcGtk (Linux)
        run: dotnet restore NcGtk/NcGtk.csproj
      - name: Build NcGtk (Linux)
        run: dotnet publish NcGtk/NcGtk.csproj -c Release -o publish/NcGtk /p:DebugType=none /p:DebugSymbols=false
      - name: Rename folder for clean archive structure
        run: |
          rm -rf NcGtk
          mv publish/NcGtk NcGtk
      - name: Archive NcGtk (Linux)
        run: zip -r NcGtk.zip NcGtk
      - name: Upload NcGtk artifact
        uses: actions/upload-artifact@v4
        with:
          name: NcGtk
          path: NcGtk.zip
